### ISSUE TITLE
PA Review: Reading Mode (#4)

### ISSUE THREAD

**Issue by kaycbas** [kaycbas/rocket#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
--------------------
Comments:
- users can open articles (from any tab) in a distraction free reading mode
-various actions can be performed from within the reading mode; available actions depend on which tab they're in (i.e. archive, home, discover)
-all actions should work (saving, archiving, favoriting, hiding)

**Comment by mkayys** [comment]
![Screen Shot 2020-12-15 at 3 20 48 PM](https://user-images.githubusercontent.com/48598856/102284516-2260bf80-3ee9-11eb-99c7-93fe2c00d9bf.png)
- I had a question about the eye icon; wasn't sure what that was for. (actually it's the hide isn't it?)
- also if I delete an article, is it forever gone?

**Comment by mkayys** [comment]
![Screen Shot 2020-12-15 at 3 25 25 PM](https://user-images.githubusercontent.com/48598856/102284826-c64a6b00-3ee9-11eb-8611-f2686c4e495c.png)
- is this a placeholder for a future feature, like highlighting?

**Comment by kaycbas** [comment]
@mkayys 
- Eye icon just hides it from the discover tab if you're not interested in that article. All hidden articles can be restored from the profile dropdown
- 'Delete' just removes articles from your 'Saves' (which includes your List, Archive, and Favorites). It will then re-appear in the Discover tab.
    - Users have no ability to permanently delete an article, only un-save and hide

**Comment by kaycbas** [comment]
I was planning to implement a feature where you could change the font size via that icon, but now I think I will remove it.
