### ISSUE TITLE
PA Review: Save via URL (#6)

### ISSUE THREAD

**Issue by kaycbas** [kaycbas/rocket#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

## Comments
- users are now able to click the '+' on the main navbar to open up a url input field
- users can paste in the url of an article, click 'Save', and the article will be added to their saved articles (including title, content, etc)
- the webscraper works pretty well for most standard looking articles and has some special optimizations for Medium articles
    - I would suggest trying some articles from here: https://medium.com/ or https://techcrunch.com/ or https://www.wired.com/
    - it's definitely not perfect yet, but I'm still improving it
- images are also pulled if the webscraper finds one of the right type and size

**Comment by mkayys** [comment]
- looks like everything is working; just had a question about when the webscrapper grabs the article, is it never truly added to discover. If I'm on the discover page and I use the feature, it shows on discover but when I navigate back it's not there
- just wanted to check in if that was a design choice

**Comment by kaycbas** [comment]
@mkayys 
- The article is supposed to go straight into the user's saved articles (My List), but if you're on the Discover page it automatically gets received into the current articles slice before another fetch is made - not really a design decision
- I'll fix that and then maybe add a message saying 'Article added to Your List' when saved from the Discover tab

**Comment by kaycbas** [comment]
@mkayys 
maybe that's not what's happening, I'll look into it
